name: CI Test for Vercel

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Set environment variables from secrets
        run: |
          echo "VITE_SGIS_CONSUMER_KEY=${{ secrets.VITE_SGIS_CONSUMER_KEY }}" >> $GITHUB_ENV
          echo "VITE_SGIS_CONSUMER_SECRET=${{ secrets.VITE_SGIS_CONSUMER_SECRET }}" >> $GITHUB_ENV
          echo "VITE_KAKAO_MAP_API_KEY=${{ secrets.VITE_KAKAO_MAP_API_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build check
        run: npm run build
